### ISSUE TITLE
System.AccessViolationException was unhandled

### ISSUE THREAD

**Issue by akatran** [joeyespo/webcam-lib#2]
`System.AccessViolationException` was unhandled:

```
Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Source=System.Drawing
StackTrace:
     at System.Drawing.SafeNativeMethods.Gdip.GdipImageRotateFlip(HandleRef image, Int32 rotateFlipType)
     at System.Drawing.Image.RotateFlip(RotateFlipType rotateFlipType)
     at WebcamLib.Webcam.FrameCallbackProc(IntPtr hWnd, VideoHeader& VideoHeader) in F:\Programming\SamplesAndExamples\joeyespo-webcam-lib-b12eab6\WebcamLib\Webcam.cs:line 361
     at WebcamLib.Win32.SendMessage(IntPtr hWnd, UInt32 Msg, Int32 wParam, Int32 lParam)
     at WebcamLib.Webcam.GrabFrame() in F:\Programming\SamplesAndExamples\joeyespo-webcam-lib-b12eab6\WebcamLib\Webcam.cs:line 245
     at WebcamLib.Webcam.PreviewTick(Object sender, EventArgs e) in F:\Programming\SamplesAndExamples\joeyespo-webcam-lib-b12eab6\WebcamLib\Webcam.cs:line 387
     at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
     at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
     at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
     at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
     at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
     at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
     at WebcamLibDemo.Program.Main() in F:\Programming\SamplesAndExamples\joeyespo-webcam-lib-b12eab6\WebcamLibDemo\Program.cs:line 24
     at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
     at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
```

Is given on:

```
try
{
    img = new Bitmap(cx, Math.Abs(cy), (((VideoHeader.dwBytesUsed > 0) ? (VideoHeader.dwBytesUsed - area) : (0)) + cbw), PixelFormat.Format24bppRgb, VideoHeader.lpData);
    if(cy > 0)
        img.RotateFlip(RotateFlipType.RotateNoneFlipY); <-- This is where AccessViolationException occurs
}
catch(NullReferenceException)
```

in the `FrameCallbackProc` method.

**Comment by akatran** [comment]
Solution is converted with Visual Studio 2010

**Comment by joeyespo** [comment]
Oh wow. That one looks nasty. I'll check this out.

If you could answer these though, it'd really help me track it down:
1. Does this occur as _soon_ as the webcam starts?
2. If you comment out the following code within the try/catch, does it work for you (and show everything upside-down)?

```
if(cy > 0)
    img.RotateFlip(RotateFlipType.RotateNoneFlipY);
```

**Comment by joeyespo** [comment]
After reading [this MSDN article](http://social.msdn.microsoft.com/Forums/en-IE/csharplanguage/thread/affa1855-e1ec-476d-bfb1-d0985971f394), I think this issue may be related. Images cannot be rotated with locked bits or random exceptions will be thrown. Perhaps the video bits are locked for edit.

I'll resolve this issue. Since my webcam is in storage right now, feel free to reopen the issue if this still happens. Either way, I'll look into this again when I get my webcam back here.

**Comment by joeyespo** [comment]
For the record, the access violation is happening because `System.Drawing` doesn't handle certain compressions. Fixing #3 will fix this.
